run:
  skip-dirs:
    - sandbox
linters-settings:
  revive:
    rules:
      - name: if-return
        severity: warning
        disabled: true
linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - unused
    - gosimple
    - revive
