package bybit

// SymbolInverse :
type SymbolInverse string

const (
	// SymbolInverse10000NFTUSDT :
	SymbolInverse10000NFTUSDT = SymbolInverse("10000NFTUSDT")
	// SymbolInverse1000BTTUSDT :
	SymbolInverse1000BTTUSDT = SymbolInverse("1000BTTUSDT")
	// SymbolInverse1000LUNCUSDT :
	SymbolInverse1000LUNCUSDT = SymbolInverse("1000LUNCUSDT")
	// SymbolInverse1000XECUSDT :
	SymbolInverse1000XECUSDT = SymbolInverse("1000XECUSDT")
	// SymbolInverse1INCHUSDT :
	SymbolInverse1INCHUSDT = SymbolInverse("1INCHUSDT")
	// SymbolInverseAAVEUSDT :
	SymbolInverseAAVEUSDT = SymbolInverse("AAVEUSDT")
	// SymbolInverseACHUSDT :
	SymbolInverseACHUSDT = SymbolInverse("ACHUSDT")
	// SymbolInverseADAUSD :
	SymbolInverseADAUSD = SymbolInverse("ADAUSD")
	// SymbolInverseADAUSDT :
	SymbolInverseADAUSDT = SymbolInverse("ADAUSDT")
	// SymbolInverseAGLDUSDT :
	SymbolInverseAGLDUSDT = SymbolInverse("AGLDUSDT")
	// SymbolInverseAKROUSDT :
	SymbolInverseAKROUSDT = SymbolInverse("AKROUSDT")
	// SymbolInverseALGOUSDT :
	SymbolInverseALGOUSDT = SymbolInverse("ALGOUSDT")
	// SymbolInverseALICEUSDT :
	SymbolInverseALICEUSDT = SymbolInverse("ALICEUSDT")
	// SymbolInverseALPHAUSDT :
	SymbolInverseALPHAUSDT = SymbolInverse("ALPHAUSDT")
	// SymbolInverseANKRUSDT :
	SymbolInverseANKRUSDT = SymbolInverse("ANKRUSDT")
	// SymbolInverseANTUSDT :
	SymbolInverseANTUSDT = SymbolInverse("ANTUSDT")
	// SymbolInverseAPEUSDT :
	SymbolInverseAPEUSDT = SymbolInverse("APEUSDT")
	// SymbolInverseAPI3USDT :
	SymbolInverseAPI3USDT = SymbolInverse("API3USDT")
	// SymbolInverseARPAUSDT :
	SymbolInverseARPAUSDT = SymbolInverse("ARPAUSDT")
	// SymbolInverseARUSDT :
	SymbolInverseARUSDT = SymbolInverse("ARUSDT")
	// SymbolInverseASTRUSDT :
	SymbolInverseASTRUSDT = SymbolInverse("ASTRUSDT")
	// SymbolInverseAUDIOUSDT :
	SymbolInverseAUDIOUSDT = SymbolInverse("AUDIOUSDT")
	// SymbolInverseAVAXUSDT :
	SymbolInverseAVAXUSDT = SymbolInverse("AVAXUSDT")
	// SymbolInverseAXSUSDT :
	SymbolInverseAXSUSDT = SymbolInverse("AXSUSDT")
	// SymbolInverseBAKEUSDT :
	SymbolInverseBAKEUSDT = SymbolInverse("BAKEUSDT")
	// SymbolInverseBALUSDT :
	SymbolInverseBALUSDT = SymbolInverse("BALUSDT")
	// SymbolInverseBANDUSDT :
	SymbolInverseBANDUSDT = SymbolInverse("BANDUSDT")
	// SymbolInverseBATUSDT :
	SymbolInverseBATUSDT = SymbolInverse("BATUSDT")
	// SymbolInverseBCHUSDT :
	SymbolInverseBCHUSDT = SymbolInverse("BCHUSDT")
	// SymbolInverseBELUSDT :
	SymbolInverseBELUSDT = SymbolInverse("BELUSDT")
	// SymbolInverseBICOUSDT :
	SymbolInverseBICOUSDT = SymbolInverse("BICOUSDT")
	// SymbolInverseBITUSD :
	SymbolInverseBITUSD = SymbolInverse("BITUSD")
	// SymbolInverseBITUSDT :
	SymbolInverseBITUSDT = SymbolInverse("BITUSDT")
	// SymbolInverseBLZUSDT :
	SymbolInverseBLZUSDT = SymbolInverse("BLZUSDT")
	// SymbolInverseBNBUSDT :
	SymbolInverseBNBUSDT = SymbolInverse("BNBUSDT")
	// SymbolInverseBNXUSDT :
	SymbolInverseBNXUSDT = SymbolInverse("BNXUSDT")
	// SymbolInverseBOBAUSDT :
	SymbolInverseBOBAUSDT = SymbolInverse("BOBAUSDT")
	// SymbolInverseBSVUSDT :
	SymbolInverseBSVUSDT = SymbolInverse("BSVUSDT")
	// SymbolInverseBSWUSDT :
	SymbolInverseBSWUSDT = SymbolInverse("BSWUSDT")
	// SymbolInverseBTCUSD :
	SymbolInverseBTCUSD = SymbolInverse("BTCUSD")
	// SymbolInverseBTCUSDH23 :
	SymbolInverseBTCUSDH23 = SymbolInverse("BTCUSDH23")
	// SymbolInverseBTCUSDT :
	SymbolInverseBTCUSDT = SymbolInverse("BTCUSDT")
	// SymbolInverseBTCUSDZ22 :
	SymbolInverseBTCUSDZ22 = SymbolInverse("BTCUSDZ22")
	// SymbolInverseC98USDT :
	SymbolInverseC98USDT = SymbolInverse("C98USDT")
	// SymbolInverseCEEKUSDT :
	SymbolInverseCEEKUSDT = SymbolInverse("CEEKUSDT")
	// SymbolInverseCELOUSDT :
	SymbolInverseCELOUSDT = SymbolInverse("CELOUSDT")
	// SymbolInverseCELRUSDT :
	SymbolInverseCELRUSDT = SymbolInverse("CELRUSDT")
	// SymbolInverseCELUSDT :
	SymbolInverseCELUSDT = SymbolInverse("CELUSDT")
	// SymbolInverseCHRUSDT :
	SymbolInverseCHRUSDT = SymbolInverse("CHRUSDT")
	// SymbolInverseCHZUSDT :
	SymbolInverseCHZUSDT = SymbolInverse("CHZUSDT")
	// SymbolInverseCKBUSDT :
	SymbolInverseCKBUSDT = SymbolInverse("CKBUSDT")
	// SymbolInverseCOMPUSDT :
	SymbolInverseCOMPUSDT = SymbolInverse("COMPUSDT")
	// SymbolInverseCOTIUSDT :
	SymbolInverseCOTIUSDT = SymbolInverse("COTIUSDT")
	// SymbolInverseCREAMUSDT :
	SymbolInverseCREAMUSDT = SymbolInverse("CREAMUSDT")
	// SymbolInverseCROUSDT :
	SymbolInverseCROUSDT = SymbolInverse("CROUSDT")
	// SymbolInverseCRVUSDT :
	SymbolInverseCRVUSDT = SymbolInverse("CRVUSDT")
	// SymbolInverseCTCUSDT :
	SymbolInverseCTCUSDT = SymbolInverse("CTCUSDT")
	// SymbolInverseCTKUSDT :
	SymbolInverseCTKUSDT = SymbolInverse("CTKUSDT")
	// SymbolInverseCTSIUSDT :
	SymbolInverseCTSIUSDT = SymbolInverse("CTSIUSDT")
	// SymbolInverseCVCUSDT :
	SymbolInverseCVCUSDT = SymbolInverse("CVCUSDT")
	// SymbolInverseCVXUSDT :
	SymbolInverseCVXUSDT = SymbolInverse("CVXUSDT")
	// SymbolInverseDARUSDT :
	SymbolInverseDARUSDT = SymbolInverse("DARUSDT")
	// SymbolInverseDASHUSDT :
	SymbolInverseDASHUSDT = SymbolInverse("DASHUSDT")
	// SymbolInverseDENTUSDT :
	SymbolInverseDENTUSDT = SymbolInverse("DENTUSDT")
	// SymbolInverseDGBUSDT :
	SymbolInverseDGBUSDT = SymbolInverse("DGBUSDT")
	// SymbolInverseDODOUSDT :
	SymbolInverseDODOUSDT = SymbolInverse("DODOUSDT")
	// SymbolInverseDOGEUSDT :
	SymbolInverseDOGEUSDT = SymbolInverse("DOGEUSDT")
	// SymbolInverseDOTUSD :
	SymbolInverseDOTUSD = SymbolInverse("DOTUSD")
	// SymbolInverseDOTUSDT :
	SymbolInverseDOTUSDT = SymbolInverse("DOTUSDT")
	// SymbolInverseDUSKUSDT :
	SymbolInverseDUSKUSDT = SymbolInverse("DUSKUSDT")
	// SymbolInverseDYDXUSDT :
	SymbolInverseDYDXUSDT = SymbolInverse("DYDXUSDT")
	// SymbolInverseEGLDUSDT :
	SymbolInverseEGLDUSDT = SymbolInverse("EGLDUSDT")
	// SymbolInverseENJUSDT :
	SymbolInverseENJUSDT = SymbolInverse("ENJUSDT")
	// SymbolInverseENSUSDT :
	SymbolInverseENSUSDT = SymbolInverse("ENSUSDT")
	// SymbolInverseEOSUSD :
	SymbolInverseEOSUSD = SymbolInverse("EOSUSD")
	// SymbolInverseEOSUSDT :
	SymbolInverseEOSUSDT = SymbolInverse("EOSUSDT")
	// SymbolInverseETCUSDT :
	SymbolInverseETCUSDT = SymbolInverse("ETCUSDT")
	// SymbolInverseETHUSD :
	SymbolInverseETHUSD = SymbolInverse("ETHUSD")
	// SymbolInverseETHUSDH23 :
	SymbolInverseETHUSDH23 = SymbolInverse("ETHUSDH23")
	// SymbolInverseETHUSDT :
	SymbolInverseETHUSDT = SymbolInverse("ETHUSDT")
	// SymbolInverseETHUSDZ22 :
	SymbolInverseETHUSDZ22 = SymbolInverse("ETHUSDZ22")
	// SymbolInverseETHWUSDT :
	SymbolInverseETHWUSDT = SymbolInverse("ETHWUSDT")
	// SymbolInverseFILUSDT :
	SymbolInverseFILUSDT = SymbolInverse("FILUSDT")
	// SymbolInverseFITFIUSDT :
	SymbolInverseFITFIUSDT = SymbolInverse("FITFIUSDT")
	// SymbolInverseFLMUSDT :
	SymbolInverseFLMUSDT = SymbolInverse("FLMUSDT")
	// SymbolInverseFLOWUSDT :
	SymbolInverseFLOWUSDT = SymbolInverse("FLOWUSDT")
	// SymbolInverseFTMUSDT :
	SymbolInverseFTMUSDT = SymbolInverse("FTMUSDT")
	// SymbolInverseFTTUSDT :
	SymbolInverseFTTUSDT = SymbolInverse("FTTUSDT")
	// SymbolInverseFXSUSDT :
	SymbolInverseFXSUSDT = SymbolInverse("FXSUSDT")
	// SymbolInverseGALAUSDT :
	SymbolInverseGALAUSDT = SymbolInverse("GALAUSDT")
	// SymbolInverseGALUSDT :
	SymbolInverseGALUSDT = SymbolInverse("GALUSDT")
	// SymbolInverseGLMRUSDT :
	SymbolInverseGLMRUSDT = SymbolInverse("GLMRUSDT")
	// SymbolInverseGMTUSDT :
	SymbolInverseGMTUSDT = SymbolInverse("GMTUSDT")
	// SymbolInverseGRTUSDT :
	SymbolInverseGRTUSDT = SymbolInverse("GRTUSDT")
	// SymbolInverseGTCUSDT :
	SymbolInverseGTCUSDT = SymbolInverse("GTCUSDT")
	// SymbolInverseHBARUSDT :
	SymbolInverseHBARUSDT = SymbolInverse("HBARUSDT")
	// SymbolInverseHNTUSDT :
	SymbolInverseHNTUSDT = SymbolInverse("HNTUSDT")
	// SymbolInverseHOTUSDT :
	SymbolInverseHOTUSDT = SymbolInverse("HOTUSDT")
	// SymbolInverseICPUSDT :
	SymbolInverseICPUSDT = SymbolInverse("ICPUSDT")
	// SymbolInverseICXUSDT :
	SymbolInverseICXUSDT = SymbolInverse("ICXUSDT")
	// SymbolInverseILVUSDT :
	SymbolInverseILVUSDT = SymbolInverse("ILVUSDT")
	// SymbolInverseIMXUSDT :
	SymbolInverseIMXUSDT = SymbolInverse("IMXUSDT")
	// SymbolInverseINJUSDT :
	SymbolInverseINJUSDT = SymbolInverse("INJUSDT")
	// SymbolInverseIOSTUSDT :
	SymbolInverseIOSTUSDT = SymbolInverse("IOSTUSDT")
	// SymbolInverseIOTAUSDT :
	SymbolInverseIOTAUSDT = SymbolInverse("IOTAUSDT")
	// SymbolInverseIOTXUSDT :
	SymbolInverseIOTXUSDT = SymbolInverse("IOTXUSDT")
	// SymbolInverseJASMYUSDT :
	SymbolInverseJASMYUSDT = SymbolInverse("JASMYUSDT")
	// SymbolInverseJSTUSDT :
	SymbolInverseJSTUSDT = SymbolInverse("JSTUSDT")
	// SymbolInverseKAVAUSDT :
	SymbolInverseKAVAUSDT = SymbolInverse("KAVAUSDT")
	// SymbolInverseKDAUSDT :
	SymbolInverseKDAUSDT = SymbolInverse("KDAUSDT")
	// SymbolInverseKLAYUSDT :
	SymbolInverseKLAYUSDT = SymbolInverse("KLAYUSDT")
	// SymbolInverseKNCUSDT :
	SymbolInverseKNCUSDT = SymbolInverse("KNCUSDT")
	// SymbolInverseKSMUSDT :
	SymbolInverseKSMUSDT = SymbolInverse("KSMUSDT")
	// SymbolInverseLDOUSDT :
	SymbolInverseLDOUSDT = SymbolInverse("LDOUSDT")
	// SymbolInverseLINAUSDT :
	SymbolInverseLINAUSDT = SymbolInverse("LINAUSDT")
	// SymbolInverseLINKUSDT :
	SymbolInverseLINKUSDT = SymbolInverse("LINKUSDT")
	// SymbolInverseLITUSDT :
	SymbolInverseLITUSDT = SymbolInverse("LITUSDT")
	// SymbolInverseLOOKSUSDT :
	SymbolInverseLOOKSUSDT = SymbolInverse("LOOKSUSDT")
	// SymbolInverseLPTUSDT :
	SymbolInverseLPTUSDT = SymbolInverse("LPTUSDT")
	// SymbolInverseLRCUSDT :
	SymbolInverseLRCUSDT = SymbolInverse("LRCUSDT")
	// SymbolInverseLTCUSD :
	SymbolInverseLTCUSD = SymbolInverse("LTCUSD")
	// SymbolInverseLTCUSDT :
	SymbolInverseLTCUSDT = SymbolInverse("LTCUSDT")
	// SymbolInverseLUNA2USDT :
	SymbolInverseLUNA2USDT = SymbolInverse("LUNA2USDT")
	// SymbolInverseMANAUSD :
	SymbolInverseMANAUSD = SymbolInverse("MANAUSD")
	// SymbolInverseMANAUSDT :
	SymbolInverseMANAUSDT = SymbolInverse("MANAUSDT")
	// SymbolInverseMASKUSDT :
	SymbolInverseMASKUSDT = SymbolInverse("MASKUSDT")
	// SymbolInverseMATICUSDT :
	SymbolInverseMATICUSDT = SymbolInverse("MATICUSDT")
	// SymbolInverseMINAUSDT :
	SymbolInverseMINAUSDT = SymbolInverse("MINAUSDT")
	// SymbolInverseMKRUSDT :
	SymbolInverseMKRUSDT = SymbolInverse("MKRUSDT")
	// SymbolInverseMTLUSDT :
	SymbolInverseMTLUSDT = SymbolInverse("MTLUSDT")
	// SymbolInverseNEARUSDT :
	SymbolInverseNEARUSDT = SymbolInverse("NEARUSDT")
	// SymbolInverseNEOUSDT :
	SymbolInverseNEOUSDT = SymbolInverse("NEOUSDT")
	// SymbolInverseOCEANUSDT :
	SymbolInverseOCEANUSDT = SymbolInverse("OCEANUSDT")
	// SymbolInverseOGNUSDT :
	SymbolInverseOGNUSDT = SymbolInverse("OGNUSDT")
	// SymbolInverseOMGUSDT :
	SymbolInverseOMGUSDT = SymbolInverse("OMGUSDT")
	// SymbolInverseONEUSDT :
	SymbolInverseONEUSDT = SymbolInverse("ONEUSDT")
	// SymbolInverseONTUSDT :
	SymbolInverseONTUSDT = SymbolInverse("ONTUSDT")
	// SymbolInverseOPUSDT :
	SymbolInverseOPUSDT = SymbolInverse("OPUSDT")
	// SymbolInversePAXGUSDT :
	SymbolInversePAXGUSDT = SymbolInverse("PAXGUSDT")
	// SymbolInversePEOPLEUSDT :
	SymbolInversePEOPLEUSDT = SymbolInverse("PEOPLEUSDT")
	// SymbolInverseQNTUSDT :
	SymbolInverseQNTUSDT = SymbolInverse("QNTUSDT")
	// SymbolInverseQTUMUSDT :
	SymbolInverseQTUMUSDT = SymbolInverse("QTUMUSDT")
	// SymbolInverseRAYUSDT :
	SymbolInverseRAYUSDT = SymbolInverse("RAYUSDT")
	// SymbolInverseREEFUSDT :
	SymbolInverseREEFUSDT = SymbolInverse("REEFUSDT")
	// SymbolInverseRENUSDT :
	SymbolInverseRENUSDT = SymbolInverse("RENUSDT")
	// SymbolInverseREQUSDT :
	SymbolInverseREQUSDT = SymbolInverse("REQUSDT")
	// SymbolInverseRNDRUSDT :
	SymbolInverseRNDRUSDT = SymbolInverse("RNDRUSDT")
	// SymbolInverseROSEUSDT :
	SymbolInverseROSEUSDT = SymbolInverse("ROSEUSDT")
	// SymbolInverseRSRUSDT :
	SymbolInverseRSRUSDT = SymbolInverse("RSRUSDT")
	// SymbolInverseRSS3USDT :
	SymbolInverseRSS3USDT = SymbolInverse("RSS3USDT")
	// SymbolInverseRUNEUSDT :
	SymbolInverseRUNEUSDT = SymbolInverse("RUNEUSDT")
	// SymbolInverseRVNUSDT :
	SymbolInverseRVNUSDT = SymbolInverse("RVNUSDT")
	// SymbolInverseSANDUSDT :
	SymbolInverseSANDUSDT = SymbolInverse("SANDUSDT")
	// SymbolInverseSCRTUSDT :
	SymbolInverseSCRTUSDT = SymbolInverse("SCRTUSDT")
	// SymbolInverseSCUSDT :
	SymbolInverseSCUSDT = SymbolInverse("SCUSDT")
	// SymbolInverseSFPUSDT :
	SymbolInverseSFPUSDT = SymbolInverse("SFPUSDT")
	// SymbolInverseSHIB1000USDT :
	SymbolInverseSHIB1000USDT = SymbolInverse("SHIB1000USDT")
	// SymbolInverseSKLUSDT :
	SymbolInverseSKLUSDT = SymbolInverse("SKLUSDT")
	// SymbolInverseSLPUSDT :
	SymbolInverseSLPUSDT = SymbolInverse("SLPUSDT")
	// SymbolInverseSNXUSDT :
	SymbolInverseSNXUSDT = SymbolInverse("SNXUSDT")
	// SymbolInverseSOLUSD :
	SymbolInverseSOLUSD = SymbolInverse("SOLUSD")
	// SymbolInverseSOLUSDT :
	SymbolInverseSOLUSDT = SymbolInverse("SOLUSDT")
	// SymbolInverseSRMUSDT :
	SymbolInverseSRMUSDT = SymbolInverse("SRMUSDT")
	// SymbolInverseSTGUSDT :
	SymbolInverseSTGUSDT = SymbolInverse("STGUSDT")
	// SymbolInverseSTMXUSDT :
	SymbolInverseSTMXUSDT = SymbolInverse("STMXUSDT")
	// SymbolInverseSTORJUSDT :
	SymbolInverseSTORJUSDT = SymbolInverse("STORJUSDT")
	// SymbolInverseSTXUSDT :
	SymbolInverseSTXUSDT = SymbolInverse("STXUSDT")
	// SymbolInverseSUNUSDT :
	SymbolInverseSUNUSDT = SymbolInverse("SUNUSDT")
	// SymbolInverseSUSHIUSDT :
	SymbolInverseSUSHIUSDT = SymbolInverse("SUSHIUSDT")
	// SymbolInverseSXPUSDT :
	SymbolInverseSXPUSDT = SymbolInverse("SXPUSDT")
	// SymbolInverseTHETAUSDT :
	SymbolInverseTHETAUSDT = SymbolInverse("THETAUSDT")
	// SymbolInverseTLMUSDT :
	SymbolInverseTLMUSDT = SymbolInverse("TLMUSDT")
	// SymbolInverseTOMOUSDT :
	SymbolInverseTOMOUSDT = SymbolInverse("TOMOUSDT")
	// SymbolInverseTRBUSDT :
	SymbolInverseTRBUSDT = SymbolInverse("TRBUSDT")
	// SymbolInverseTRXUSDT :
	SymbolInverseTRXUSDT = SymbolInverse("TRXUSDT")
	// SymbolInverseUNFIUSDT :
	SymbolInverseUNFIUSDT = SymbolInverse("UNFIUSDT")
	// SymbolInverseUNIUSDT :
	SymbolInverseUNIUSDT = SymbolInverse("UNIUSDT")
	// SymbolInverseUSDCUSDT :
	SymbolInverseUSDCUSDT = SymbolInverse("USDCUSDT")
	// SymbolInverseVETUSDT :
	SymbolInverseVETUSDT = SymbolInverse("VETUSDT")
	// SymbolInverseWAVESUSDT :
	SymbolInverseWAVESUSDT = SymbolInverse("WAVESUSDT")
	// SymbolInverseWOOUSDT :
	SymbolInverseWOOUSDT = SymbolInverse("WOOUSDT")
	// SymbolInverseXEMUSDT :
	SymbolInverseXEMUSDT = SymbolInverse("XEMUSDT")
	// SymbolInverseXLMUSDT :
	SymbolInverseXLMUSDT = SymbolInverse("XLMUSDT")
	// SymbolInverseXMRUSDT :
	SymbolInverseXMRUSDT = SymbolInverse("XMRUSDT")
	// SymbolInverseXNOUSDT :
	SymbolInverseXNOUSDT = SymbolInverse("XNOUSDT")
	// SymbolInverseXRPUSD :
	SymbolInverseXRPUSD = SymbolInverse("XRPUSD")
	// SymbolInverseXRPUSDT :
	SymbolInverseXRPUSDT = SymbolInverse("XRPUSDT")
	// SymbolInverseXTZUSDT :
	SymbolInverseXTZUSDT = SymbolInverse("XTZUSDT")
	// SymbolInverseYFIUSDT :
	SymbolInverseYFIUSDT = SymbolInverse("YFIUSDT")
	// SymbolInverseYGGUSDT :
	SymbolInverseYGGUSDT = SymbolInverse("YGGUSDT")
	// SymbolInverseZECUSDT :
	SymbolInverseZECUSDT = SymbolInverse("ZECUSDT")
	// SymbolInverseZENUSDT :
	SymbolInverseZENUSDT = SymbolInverse("ZENUSDT")
	// SymbolInverseZILUSDT :
	SymbolInverseZILUSDT = SymbolInverse("ZILUSDT")
	// SymbolInverseZRXUSDT :
	SymbolInverseZRXUSDT = SymbolInverse("ZRXUSDT")
)
