package bybit

// SymbolFuture :
type SymbolFuture string

const (
	// SymbolFuture10000NFTUSDT :
	SymbolFuture10000NFTUSDT = SymbolFuture("10000NFTUSDT")
	// SymbolFuture1000BTTUSDT :
	SymbolFuture1000BTTUSDT = SymbolFuture("1000BTTUSDT")
	// SymbolFuture1000LUNCUSDT :
	SymbolFuture1000LUNCUSDT = SymbolFuture("1000LUNCUSDT")
	// SymbolFuture1000XECUSDT :
	SymbolFuture1000XECUSDT = SymbolFuture("1000XECUSDT")
	// SymbolFuture1INCHUSDT :
	SymbolFuture1INCHUSDT = SymbolFuture("1INCHUSDT")
	// SymbolFutureAAVEUSDT :
	SymbolFutureAAVEUSDT = SymbolFuture("AAVEUSDT")
	// SymbolFutureACHUSDT :
	SymbolFutureACHUSDT = SymbolFuture("ACHUSDT")
	// SymbolFutureADAUSD :
	SymbolFutureADAUSD = SymbolFuture("ADAUSD")
	// SymbolFutureADAUSDT :
	SymbolFutureADAUSDT = SymbolFuture("ADAUSDT")
	// SymbolFutureAGLDUSDT :
	SymbolFutureAGLDUSDT = SymbolFuture("AGLDUSDT")
	// SymbolFutureAKROUSDT :
	SymbolFutureAKROUSDT = SymbolFuture("AKROUSDT")
	// SymbolFutureALGOUSDT :
	SymbolFutureALGOUSDT = SymbolFuture("ALGOUSDT")
	// SymbolFutureALICEUSDT :
	SymbolFutureALICEUSDT = SymbolFuture("ALICEUSDT")
	// SymbolFutureALPHAUSDT :
	SymbolFutureALPHAUSDT = SymbolFuture("ALPHAUSDT")
	// SymbolFutureANKRUSDT :
	SymbolFutureANKRUSDT = SymbolFuture("ANKRUSDT")
	// SymbolFutureANTUSDT :
	SymbolFutureANTUSDT = SymbolFuture("ANTUSDT")
	// SymbolFutureAPEUSDT :
	SymbolFutureAPEUSDT = SymbolFuture("APEUSDT")
	// SymbolFutureAPI3USDT :
	SymbolFutureAPI3USDT = SymbolFuture("API3USDT")
	// SymbolFutureARPAUSDT :
	SymbolFutureARPAUSDT = SymbolFuture("ARPAUSDT")
	// SymbolFutureARUSDT :
	SymbolFutureARUSDT = SymbolFuture("ARUSDT")
	// SymbolFutureASTRUSDT :
	SymbolFutureASTRUSDT = SymbolFuture("ASTRUSDT")
	// SymbolFutureAUDIOUSDT :
	SymbolFutureAUDIOUSDT = SymbolFuture("AUDIOUSDT")
	// SymbolFutureAVAXUSDT :
	SymbolFutureAVAXUSDT = SymbolFuture("AVAXUSDT")
	// SymbolFutureAXSUSDT :
	SymbolFutureAXSUSDT = SymbolFuture("AXSUSDT")
	// SymbolFutureBAKEUSDT :
	SymbolFutureBAKEUSDT = SymbolFuture("BAKEUSDT")
	// SymbolFutureBALUSDT :
	SymbolFutureBALUSDT = SymbolFuture("BALUSDT")
	// SymbolFutureBANDUSDT :
	SymbolFutureBANDUSDT = SymbolFuture("BANDUSDT")
	// SymbolFutureBATUSDT :
	SymbolFutureBATUSDT = SymbolFuture("BATUSDT")
	// SymbolFutureBCHUSDT :
	SymbolFutureBCHUSDT = SymbolFuture("BCHUSDT")
	// SymbolFutureBELUSDT :
	SymbolFutureBELUSDT = SymbolFuture("BELUSDT")
	// SymbolFutureBICOUSDT :
	SymbolFutureBICOUSDT = SymbolFuture("BICOUSDT")
	// SymbolFutureBITUSD :
	SymbolFutureBITUSD = SymbolFuture("BITUSD")
	// SymbolFutureBITUSDT :
	SymbolFutureBITUSDT = SymbolFuture("BITUSDT")
	// SymbolFutureBLZUSDT :
	SymbolFutureBLZUSDT = SymbolFuture("BLZUSDT")
	// SymbolFutureBNBUSDT :
	SymbolFutureBNBUSDT = SymbolFuture("BNBUSDT")
	// SymbolFutureBNXUSDT :
	SymbolFutureBNXUSDT = SymbolFuture("BNXUSDT")
	// SymbolFutureBOBAUSDT :
	SymbolFutureBOBAUSDT = SymbolFuture("BOBAUSDT")
	// SymbolFutureBSVUSDT :
	SymbolFutureBSVUSDT = SymbolFuture("BSVUSDT")
	// SymbolFutureBSWUSDT :
	SymbolFutureBSWUSDT = SymbolFuture("BSWUSDT")
	// SymbolFutureBTCUSD :
	SymbolFutureBTCUSD = SymbolFuture("BTCUSD")
	// SymbolFutureBTCUSDH23 :
	SymbolFutureBTCUSDH23 = SymbolFuture("BTCUSDH23")
	// SymbolFutureBTCUSDT :
	SymbolFutureBTCUSDT = SymbolFuture("BTCUSDT")
	// SymbolFutureBTCUSDZ22 :
	SymbolFutureBTCUSDZ22 = SymbolFuture("BTCUSDZ22")
	// SymbolFutureC98USDT :
	SymbolFutureC98USDT = SymbolFuture("C98USDT")
	// SymbolFutureCEEKUSDT :
	SymbolFutureCEEKUSDT = SymbolFuture("CEEKUSDT")
	// SymbolFutureCELOUSDT :
	SymbolFutureCELOUSDT = SymbolFuture("CELOUSDT")
	// SymbolFutureCELRUSDT :
	SymbolFutureCELRUSDT = SymbolFuture("CELRUSDT")
	// SymbolFutureCELUSDT :
	SymbolFutureCELUSDT = SymbolFuture("CELUSDT")
	// SymbolFutureCHRUSDT :
	SymbolFutureCHRUSDT = SymbolFuture("CHRUSDT")
	// SymbolFutureCHZUSDT :
	SymbolFutureCHZUSDT = SymbolFuture("CHZUSDT")
	// SymbolFutureCKBUSDT :
	SymbolFutureCKBUSDT = SymbolFuture("CKBUSDT")
	// SymbolFutureCOMPUSDT :
	SymbolFutureCOMPUSDT = SymbolFuture("COMPUSDT")
	// SymbolFutureCOTIUSDT :
	SymbolFutureCOTIUSDT = SymbolFuture("COTIUSDT")
	// SymbolFutureCREAMUSDT :
	SymbolFutureCREAMUSDT = SymbolFuture("CREAMUSDT")
	// SymbolFutureCROUSDT :
	SymbolFutureCROUSDT = SymbolFuture("CROUSDT")
	// SymbolFutureCRVUSDT :
	SymbolFutureCRVUSDT = SymbolFuture("CRVUSDT")
	// SymbolFutureCTCUSDT :
	SymbolFutureCTCUSDT = SymbolFuture("CTCUSDT")
	// SymbolFutureCTKUSDT :
	SymbolFutureCTKUSDT = SymbolFuture("CTKUSDT")
	// SymbolFutureCTSIUSDT :
	SymbolFutureCTSIUSDT = SymbolFuture("CTSIUSDT")
	// SymbolFutureCVCUSDT :
	SymbolFutureCVCUSDT = SymbolFuture("CVCUSDT")
	// SymbolFutureCVXUSDT :
	SymbolFutureCVXUSDT = SymbolFuture("CVXUSDT")
	// SymbolFutureDARUSDT :
	SymbolFutureDARUSDT = SymbolFuture("DARUSDT")
	// SymbolFutureDASHUSDT :
	SymbolFutureDASHUSDT = SymbolFuture("DASHUSDT")
	// SymbolFutureDENTUSDT :
	SymbolFutureDENTUSDT = SymbolFuture("DENTUSDT")
	// SymbolFutureDGBUSDT :
	SymbolFutureDGBUSDT = SymbolFuture("DGBUSDT")
	// SymbolFutureDODOUSDT :
	SymbolFutureDODOUSDT = SymbolFuture("DODOUSDT")
	// SymbolFutureDOGEUSDT :
	SymbolFutureDOGEUSDT = SymbolFuture("DOGEUSDT")
	// SymbolFutureDOTUSD :
	SymbolFutureDOTUSD = SymbolFuture("DOTUSD")
	// SymbolFutureDOTUSDT :
	SymbolFutureDOTUSDT = SymbolFuture("DOTUSDT")
	// SymbolFutureDUSKUSDT :
	SymbolFutureDUSKUSDT = SymbolFuture("DUSKUSDT")
	// SymbolFutureDYDXUSDT :
	SymbolFutureDYDXUSDT = SymbolFuture("DYDXUSDT")
	// SymbolFutureEGLDUSDT :
	SymbolFutureEGLDUSDT = SymbolFuture("EGLDUSDT")
	// SymbolFutureENJUSDT :
	SymbolFutureENJUSDT = SymbolFuture("ENJUSDT")
	// SymbolFutureENSUSDT :
	SymbolFutureENSUSDT = SymbolFuture("ENSUSDT")
	// SymbolFutureEOSUSD :
	SymbolFutureEOSUSD = SymbolFuture("EOSUSD")
	// SymbolFutureEOSUSDT :
	SymbolFutureEOSUSDT = SymbolFuture("EOSUSDT")
	// SymbolFutureETCUSDT :
	SymbolFutureETCUSDT = SymbolFuture("ETCUSDT")
	// SymbolFutureETHUSD :
	SymbolFutureETHUSD = SymbolFuture("ETHUSD")
	// SymbolFutureETHUSDH23 :
	SymbolFutureETHUSDH23 = SymbolFuture("ETHUSDH23")
	// SymbolFutureETHUSDT :
	SymbolFutureETHUSDT = SymbolFuture("ETHUSDT")
	// SymbolFutureETHUSDZ22 :
	SymbolFutureETHUSDZ22 = SymbolFuture("ETHUSDZ22")
	// SymbolFutureETHWUSDT :
	SymbolFutureETHWUSDT = SymbolFuture("ETHWUSDT")
	// SymbolFutureFILUSDT :
	SymbolFutureFILUSDT = SymbolFuture("FILUSDT")
	// SymbolFutureFITFIUSDT :
	SymbolFutureFITFIUSDT = SymbolFuture("FITFIUSDT")
	// SymbolFutureFLMUSDT :
	SymbolFutureFLMUSDT = SymbolFuture("FLMUSDT")
	// SymbolFutureFLOWUSDT :
	SymbolFutureFLOWUSDT = SymbolFuture("FLOWUSDT")
	// SymbolFutureFTMUSDT :
	SymbolFutureFTMUSDT = SymbolFuture("FTMUSDT")
	// SymbolFutureFTTUSDT :
	SymbolFutureFTTUSDT = SymbolFuture("FTTUSDT")
	// SymbolFutureFXSUSDT :
	SymbolFutureFXSUSDT = SymbolFuture("FXSUSDT")
	// SymbolFutureGALAUSDT :
	SymbolFutureGALAUSDT = SymbolFuture("GALAUSDT")
	// SymbolFutureGALUSDT :
	SymbolFutureGALUSDT = SymbolFuture("GALUSDT")
	// SymbolFutureGLMRUSDT :
	SymbolFutureGLMRUSDT = SymbolFuture("GLMRUSDT")
	// SymbolFutureGMTUSDT :
	SymbolFutureGMTUSDT = SymbolFuture("GMTUSDT")
	// SymbolFutureGRTUSDT :
	SymbolFutureGRTUSDT = SymbolFuture("GRTUSDT")
	// SymbolFutureGTCUSDT :
	SymbolFutureGTCUSDT = SymbolFuture("GTCUSDT")
	// SymbolFutureHBARUSDT :
	SymbolFutureHBARUSDT = SymbolFuture("HBARUSDT")
	// SymbolFutureHNTUSDT :
	SymbolFutureHNTUSDT = SymbolFuture("HNTUSDT")
	// SymbolFutureHOTUSDT :
	SymbolFutureHOTUSDT = SymbolFuture("HOTUSDT")
	// SymbolFutureICPUSDT :
	SymbolFutureICPUSDT = SymbolFuture("ICPUSDT")
	// SymbolFutureICXUSDT :
	SymbolFutureICXUSDT = SymbolFuture("ICXUSDT")
	// SymbolFutureILVUSDT :
	SymbolFutureILVUSDT = SymbolFuture("ILVUSDT")
	// SymbolFutureIMXUSDT :
	SymbolFutureIMXUSDT = SymbolFuture("IMXUSDT")
	// SymbolFutureINJUSDT :
	SymbolFutureINJUSDT = SymbolFuture("INJUSDT")
	// SymbolFutureIOSTUSDT :
	SymbolFutureIOSTUSDT = SymbolFuture("IOSTUSDT")
	// SymbolFutureIOTAUSDT :
	SymbolFutureIOTAUSDT = SymbolFuture("IOTAUSDT")
	// SymbolFutureIOTXUSDT :
	SymbolFutureIOTXUSDT = SymbolFuture("IOTXUSDT")
	// SymbolFutureJASMYUSDT :
	SymbolFutureJASMYUSDT = SymbolFuture("JASMYUSDT")
	// SymbolFutureJSTUSDT :
	SymbolFutureJSTUSDT = SymbolFuture("JSTUSDT")
	// SymbolFutureKAVAUSDT :
	SymbolFutureKAVAUSDT = SymbolFuture("KAVAUSDT")
	// SymbolFutureKDAUSDT :
	SymbolFutureKDAUSDT = SymbolFuture("KDAUSDT")
	// SymbolFutureKLAYUSDT :
	SymbolFutureKLAYUSDT = SymbolFuture("KLAYUSDT")
	// SymbolFutureKNCUSDT :
	SymbolFutureKNCUSDT = SymbolFuture("KNCUSDT")
	// SymbolFutureKSMUSDT :
	SymbolFutureKSMUSDT = SymbolFuture("KSMUSDT")
	// SymbolFutureLDOUSDT :
	SymbolFutureLDOUSDT = SymbolFuture("LDOUSDT")
	// SymbolFutureLINAUSDT :
	SymbolFutureLINAUSDT = SymbolFuture("LINAUSDT")
	// SymbolFutureLINKUSDT :
	SymbolFutureLINKUSDT = SymbolFuture("LINKUSDT")
	// SymbolFutureLITUSDT :
	SymbolFutureLITUSDT = SymbolFuture("LITUSDT")
	// SymbolFutureLOOKSUSDT :
	SymbolFutureLOOKSUSDT = SymbolFuture("LOOKSUSDT")
	// SymbolFutureLPTUSDT :
	SymbolFutureLPTUSDT = SymbolFuture("LPTUSDT")
	// SymbolFutureLRCUSDT :
	SymbolFutureLRCUSDT = SymbolFuture("LRCUSDT")
	// SymbolFutureLTCUSD :
	SymbolFutureLTCUSD = SymbolFuture("LTCUSD")
	// SymbolFutureLTCUSDT :
	SymbolFutureLTCUSDT = SymbolFuture("LTCUSDT")
	// SymbolFutureLUNA2USDT :
	SymbolFutureLUNA2USDT = SymbolFuture("LUNA2USDT")
	// SymbolFutureMANAUSD :
	SymbolFutureMANAUSD = SymbolFuture("MANAUSD")
	// SymbolFutureMANAUSDT :
	SymbolFutureMANAUSDT = SymbolFuture("MANAUSDT")
	// SymbolFutureMASKUSDT :
	SymbolFutureMASKUSDT = SymbolFuture("MASKUSDT")
	// SymbolFutureMATICUSDT :
	SymbolFutureMATICUSDT = SymbolFuture("MATICUSDT")
	// SymbolFutureMINAUSDT :
	SymbolFutureMINAUSDT = SymbolFuture("MINAUSDT")
	// SymbolFutureMKRUSDT :
	SymbolFutureMKRUSDT = SymbolFuture("MKRUSDT")
	// SymbolFutureMTLUSDT :
	SymbolFutureMTLUSDT = SymbolFuture("MTLUSDT")
	// SymbolFutureNEARUSDT :
	SymbolFutureNEARUSDT = SymbolFuture("NEARUSDT")
	// SymbolFutureNEOUSDT :
	SymbolFutureNEOUSDT = SymbolFuture("NEOUSDT")
	// SymbolFutureOCEANUSDT :
	SymbolFutureOCEANUSDT = SymbolFuture("OCEANUSDT")
	// SymbolFutureOGNUSDT :
	SymbolFutureOGNUSDT = SymbolFuture("OGNUSDT")
	// SymbolFutureOMGUSDT :
	SymbolFutureOMGUSDT = SymbolFuture("OMGUSDT")
	// SymbolFutureONEUSDT :
	SymbolFutureONEUSDT = SymbolFuture("ONEUSDT")
	// SymbolFutureONTUSDT :
	SymbolFutureONTUSDT = SymbolFuture("ONTUSDT")
	// SymbolFutureOPUSDT :
	SymbolFutureOPUSDT = SymbolFuture("OPUSDT")
	// SymbolFuturePAXGUSDT :
	SymbolFuturePAXGUSDT = SymbolFuture("PAXGUSDT")
	// SymbolFuturePEOPLEUSDT :
	SymbolFuturePEOPLEUSDT = SymbolFuture("PEOPLEUSDT")
	// SymbolFutureQNTUSDT :
	SymbolFutureQNTUSDT = SymbolFuture("QNTUSDT")
	// SymbolFutureQTUMUSDT :
	SymbolFutureQTUMUSDT = SymbolFuture("QTUMUSDT")
	// SymbolFutureRAYUSDT :
	SymbolFutureRAYUSDT = SymbolFuture("RAYUSDT")
	// SymbolFutureREEFUSDT :
	SymbolFutureREEFUSDT = SymbolFuture("REEFUSDT")
	// SymbolFutureRENUSDT :
	SymbolFutureRENUSDT = SymbolFuture("RENUSDT")
	// SymbolFutureREQUSDT :
	SymbolFutureREQUSDT = SymbolFuture("REQUSDT")
	// SymbolFutureRNDRUSDT :
	SymbolFutureRNDRUSDT = SymbolFuture("RNDRUSDT")
	// SymbolFutureROSEUSDT :
	SymbolFutureROSEUSDT = SymbolFuture("ROSEUSDT")
	// SymbolFutureRSRUSDT :
	SymbolFutureRSRUSDT = SymbolFuture("RSRUSDT")
	// SymbolFutureRSS3USDT :
	SymbolFutureRSS3USDT = SymbolFuture("RSS3USDT")
	// SymbolFutureRUNEUSDT :
	SymbolFutureRUNEUSDT = SymbolFuture("RUNEUSDT")
	// SymbolFutureRVNUSDT :
	SymbolFutureRVNUSDT = SymbolFuture("RVNUSDT")
	// SymbolFutureSANDUSDT :
	SymbolFutureSANDUSDT = SymbolFuture("SANDUSDT")
	// SymbolFutureSCRTUSDT :
	SymbolFutureSCRTUSDT = SymbolFuture("SCRTUSDT")
	// SymbolFutureSCUSDT :
	SymbolFutureSCUSDT = SymbolFuture("SCUSDT")
	// SymbolFutureSFPUSDT :
	SymbolFutureSFPUSDT = SymbolFuture("SFPUSDT")
	// SymbolFutureSHIB1000USDT :
	SymbolFutureSHIB1000USDT = SymbolFuture("SHIB1000USDT")
	// SymbolFutureSKLUSDT :
	SymbolFutureSKLUSDT = SymbolFuture("SKLUSDT")
	// SymbolFutureSLPUSDT :
	SymbolFutureSLPUSDT = SymbolFuture("SLPUSDT")
	// SymbolFutureSNXUSDT :
	SymbolFutureSNXUSDT = SymbolFuture("SNXUSDT")
	// SymbolFutureSOLUSD :
	SymbolFutureSOLUSD = SymbolFuture("SOLUSD")
	// SymbolFutureSOLUSDT :
	SymbolFutureSOLUSDT = SymbolFuture("SOLUSDT")
	// SymbolFutureSRMUSDT :
	SymbolFutureSRMUSDT = SymbolFuture("SRMUSDT")
	// SymbolFutureSTGUSDT :
	SymbolFutureSTGUSDT = SymbolFuture("STGUSDT")
	// SymbolFutureSTMXUSDT :
	SymbolFutureSTMXUSDT = SymbolFuture("STMXUSDT")
	// SymbolFutureSTORJUSDT :
	SymbolFutureSTORJUSDT = SymbolFuture("STORJUSDT")
	// SymbolFutureSTXUSDT :
	SymbolFutureSTXUSDT = SymbolFuture("STXUSDT")
	// SymbolFutureSUNUSDT :
	SymbolFutureSUNUSDT = SymbolFuture("SUNUSDT")
	// SymbolFutureSUSHIUSDT :
	SymbolFutureSUSHIUSDT = SymbolFuture("SUSHIUSDT")
	// SymbolFutureSXPUSDT :
	SymbolFutureSXPUSDT = SymbolFuture("SXPUSDT")
	// SymbolFutureTHETAUSDT :
	SymbolFutureTHETAUSDT = SymbolFuture("THETAUSDT")
	// SymbolFutureTLMUSDT :
	SymbolFutureTLMUSDT = SymbolFuture("TLMUSDT")
	// SymbolFutureTOMOUSDT :
	SymbolFutureTOMOUSDT = SymbolFuture("TOMOUSDT")
	// SymbolFutureTRBUSDT :
	SymbolFutureTRBUSDT = SymbolFuture("TRBUSDT")
	// SymbolFutureTRXUSDT :
	SymbolFutureTRXUSDT = SymbolFuture("TRXUSDT")
	// SymbolFutureUNFIUSDT :
	SymbolFutureUNFIUSDT = SymbolFuture("UNFIUSDT")
	// SymbolFutureUNIUSDT :
	SymbolFutureUNIUSDT = SymbolFuture("UNIUSDT")
	// SymbolFutureUSDCUSDT :
	SymbolFutureUSDCUSDT = SymbolFuture("USDCUSDT")
	// SymbolFutureVETUSDT :
	SymbolFutureVETUSDT = SymbolFuture("VETUSDT")
	// SymbolFutureWAVESUSDT :
	SymbolFutureWAVESUSDT = SymbolFuture("WAVESUSDT")
	// SymbolFutureWOOUSDT :
	SymbolFutureWOOUSDT = SymbolFuture("WOOUSDT")
	// SymbolFutureXEMUSDT :
	SymbolFutureXEMUSDT = SymbolFuture("XEMUSDT")
	// SymbolFutureXLMUSDT :
	SymbolFutureXLMUSDT = SymbolFuture("XLMUSDT")
	// SymbolFutureXMRUSDT :
	SymbolFutureXMRUSDT = SymbolFuture("XMRUSDT")
	// SymbolFutureXNOUSDT :
	SymbolFutureXNOUSDT = SymbolFuture("XNOUSDT")
	// SymbolFutureXRPUSD :
	SymbolFutureXRPUSD = SymbolFuture("XRPUSD")
	// SymbolFutureXRPUSDT :
	SymbolFutureXRPUSDT = SymbolFuture("XRPUSDT")
	// SymbolFutureXTZUSDT :
	SymbolFutureXTZUSDT = SymbolFuture("XTZUSDT")
	// SymbolFutureYFIUSDT :
	SymbolFutureYFIUSDT = SymbolFuture("YFIUSDT")
	// SymbolFutureYGGUSDT :
	SymbolFutureYGGUSDT = SymbolFuture("YGGUSDT")
	// SymbolFutureZECUSDT :
	SymbolFutureZECUSDT = SymbolFuture("ZECUSDT")
	// SymbolFutureZENUSDT :
	SymbolFutureZENUSDT = SymbolFuture("ZENUSDT")
	// SymbolFutureZILUSDT :
	SymbolFutureZILUSDT = SymbolFuture("ZILUSDT")
	// SymbolFutureZRXUSDT :
	SymbolFutureZRXUSDT = SymbolFuture("ZRXUSDT")
)

// TriggerByFuture :
type TriggerByFuture string

const (
	// TriggerByFutureUNKNOWN : only for response
	TriggerByFutureUNKNOWN = TriggerByFuture("UNKNOWN")
	// TriggerByFutureLastPrice :
	TriggerByFutureLastPrice = TriggerByFuture("LastPrice")
	// TriggerByFutureIndexPrice :
	TriggerByFutureIndexPrice = TriggerByFuture("IndexPrice")
	// TriggerByFutureMarkPrice :
	TriggerByFutureMarkPrice = TriggerByFuture("MarkPrice")
)

// StopOrderTypeFuture :
type StopOrderTypeFuture string

const (
	// StopOrderTypeFutureTakeProfit :
	StopOrderTypeFutureTakeProfit = StopOrderTypeFuture("TakeProfit")
	// StopOrderTypeFutureStopLoss :
	StopOrderTypeFutureStopLoss = StopOrderTypeFuture("StopLoss")
	// StopOrderTypeFutureTrailingStop :
	StopOrderTypeFutureTrailingStop = StopOrderTypeFuture("TrailingStop")
	// StopOrderTypeFutureStop :
	StopOrderTypeFutureStop = StopOrderTypeFuture("Stop")
)
