package bybit

// TimeInForceSpot :
type TimeInForceSpot string

const (
	// TimeInForceSpotGTC :
	TimeInForceSpotGTC = TimeInForceSpot("GTC")
	// TimeInForceSpotFOK :
	TimeInForceSpotFOK = TimeInForceSpot("FOK")
	// TimeInForceSpotIOC :
	TimeInForceSpotIOC = TimeInForceSpot("IOC")
)

// SpotInterval :
type SpotInterval string

const (
	// SpotInterval1m :
	SpotInterval1m = Interval("1m")
	// SpotInterval3m :
	SpotInterval3m = Interval("3m")
	// SpotInterval5m :
	SpotInterval5m = Interval("5m")
	// SpotInterval15m :
	SpotInterval15m = Interval("15m")
	// SpotInterval30m :
	SpotInterval30m = Interval("30m")
	// SpotInterval1h :
	SpotInterval1h = Interval("1h")
	// SpotInterval2h :
	SpotInterval2h = Interval("2h")
	// SpotInterval4h :
	SpotInterval4h = Interval("4h")
	// SpotInterval6h :
	SpotInterval6h = Interval("6h")
	// SpotInterval12h :
	SpotInterval12h = Interval("12h")
	// SpotInterval1d :
	SpotInterval1d = Interval("1d")
	// SpotInterval1w :
	SpotInterval1w = Interval("1w")
	// SpotInterval1M :
	SpotInterval1M = Interval("1M")
)

// OrderTypeSpot :
type OrderTypeSpot string

const (
	// OrderTypeSpotLimit :
	OrderTypeSpotLimit = OrderTypeSpot("LIMIT")
	// OrderTypeSpotMarket :
	OrderTypeSpotMarket = OrderTypeSpot("MARKET")
	// OrderTypeSpotLimitMaker :
	OrderTypeSpotLimitMaker = OrderTypeSpot("LIMIT_MAKER")
)

// OrderStatusSpot :
type OrderStatusSpot string

const (
	// OrderStatusSpotNew :
	OrderStatusSpotNew = OrderStatusSpot("NEW")
	// OrderStatusSpotPartiallyFilled :
	OrderStatusSpotPartiallyFilled = OrderStatusSpot("PARTIALLY_FILLED")
	// OrderStatusSpotFilled :
	OrderStatusSpotFilled = OrderStatusSpot("FILLED")
	// OrderStatusSpotCanceled :
	OrderStatusSpotCanceled = OrderStatusSpot("CANCELED")
	// OrderStatusSpotPendingCancel :
	OrderStatusSpotPendingCancel = OrderStatusSpot("PENDING_CANCEL")
	// OrderStatusSpotPendingNew :
	OrderStatusSpotPendingNew = OrderStatusSpot("PENDING_NEW")
	// OrderStatusSpotRejected :
	OrderStatusSpotRejected = OrderStatusSpot("REJECTED")
)

// SymbolSpot :
type SymbolSpot string

const (
	// SymbolSpotBTCUSDT :
	SymbolSpotBTCUSDT = SymbolSpot("BTCUSDT")
	// SymbolSpotETHUSDT :
	SymbolSpotETHUSDT = SymbolSpot("ETHUSDT")
	// SymbolSpotEOSUSDT :
	SymbolSpotEOSUSDT = SymbolSpot("EOSUSDT")
	// SymbolSpotNEOBTC :
	SymbolSpotNEOBTC = SymbolSpot("NEOBTC")
	// SymbolSpotXRPUSDT :
	SymbolSpotXRPUSDT = SymbolSpot("XRPUSDT")
	// SymbolSpotUNIUSDT :
	SymbolSpotUNIUSDT = SymbolSpot("UNIUSDT")
	// SymbolSpotUNIBTC :
	SymbolSpotUNIBTC = SymbolSpot("UNIBTC")
	// SymbolSpotDOTUSDT :
	SymbolSpotDOTUSDT = SymbolSpot("DOTUSDT")
	// SymbolSpotETHBTC :
	SymbolSpotETHBTC = SymbolSpot("ETHBTC")
	// SymbolSpotEOSETH :
	SymbolSpotEOSETH = SymbolSpot("EOSETH")
	// SymbolSpotBTCETH :
	SymbolSpotBTCETH = SymbolSpot("BTCETH")
	// SymbolSpotBTTUSDT :
	SymbolSpotBTTUSDT = SymbolSpot("BTTUSDT")
	// SymbolSpotXLMUSDT :
	SymbolSpotXLMUSDT = SymbolSpot("XLMUSDT")
	// SymbolSpotLTCUSDT :
	SymbolSpotLTCUSDT = SymbolSpot("LTCUSDT")
	// SymbolSpotXRPBTC :
	SymbolSpotXRPBTC = SymbolSpot("XRPBTC")
	// SymbolSpotXRPEOS :
	SymbolSpotXRPEOS = SymbolSpot("XRPEOS")
	// SymbolSpotDOGEUSDT :
	SymbolSpotDOGEUSDT = SymbolSpot("DOGEUSDT")
	// SymbolSpotBITUSDT :
	SymbolSpotBITUSDT = SymbolSpot("BITUSDT")
	// SymbolSpotADAUSDT :
	SymbolSpotADAUSDT = SymbolSpot("ADAUSDT")
	// SymbolSpotXTZUSDT :
	SymbolSpotXTZUSDT = SymbolSpot("XTZUSDT")
	// SymbolSpotAXSUSDT :
	SymbolSpotAXSUSDT = SymbolSpot("AXSUSDT")
	// SymbolSpotDYDXUSDT :
	SymbolSpotDYDXUSDT = SymbolSpot("DYDXUSDT")
	// SymbolSpotPMTEST2USDT :
	SymbolSpotPMTEST2USDT = SymbolSpot("PMTEST2USDT")
	// SymbolSpotPERPUSDT :
	SymbolSpotPERPUSDT = SymbolSpot("PERPUSDT")
	// SymbolSpotGRTUSDT :
	SymbolSpotGRTUSDT = SymbolSpot("GRTUSDT")
	// SymbolSpotUSDCUSDT :
	SymbolSpotUSDCUSDT = SymbolSpot("USDCUSDT")
	// SymbolSpotSOLUSDT :
	SymbolSpotSOLUSDT = SymbolSpot("SOLUSDT")
	// SymbolSpotOMGUSDT :
	SymbolSpotOMGUSDT = SymbolSpot("OMGUSDT")
	// SymbolSpotLUNCUSDT :
	SymbolSpotLUNCUSDT = SymbolSpot("LUNCUSDT")
	// SymbolSpotPMTEST15USDT :
	SymbolSpotPMTEST15USDT = SymbolSpot("PMTEST15USDT")
	// SymbolSpotICPETH :
	SymbolSpotICPETH = SymbolSpot("ICPETH")
	// SymbolSpotPMTEST7ETH :
	SymbolSpotPMTEST7ETH = SymbolSpot("PMTEST7ETH")
	// SymbolSpotBTCUSDC :
	SymbolSpotBTCUSDC = SymbolSpot("BTCUSDC")
	// SymbolSpotETHUSDC :
	SymbolSpotETHUSDC = SymbolSpot("ETHUSDC")
	// SymbolSpotBITETH :
	SymbolSpotBITETH = SymbolSpot("BITETH")
	// SymbolSpotPMTEST8PMTEST7 :
	SymbolSpotPMTEST8PMTEST7 = SymbolSpot("PMTEST8PMTEST7")
	// SymbolSpotPMTEST7USDC :
	SymbolSpotPMTEST7USDC = SymbolSpot("PMTEST7USDC")
	// SymbolSpotPMTEST8USDC :
	SymbolSpotPMTEST8USDC = SymbolSpot("PMTEST8USDC")
	// SymbolSpotUSDTBIT :
	SymbolSpotUSDTBIT = SymbolSpot("USDTBIT")
	// SymbolSpotXRP3LUSDT :
	SymbolSpotXRP3LUSDT = SymbolSpot("XRP3LUSDT")
	// SymbolSpotXRP3SUSDT :
	SymbolSpotXRP3SUSDT = SymbolSpot("XRP3SUSDT")
	// SymbolSpotUNIBIT :
	SymbolSpotUNIBIT = SymbolSpot("UNIBIT")
	// SymbolSpotUSDTTESTNETCS1 :
	SymbolSpotUSDTTESTNETCS1 = SymbolSpot("USDTTESTNETCS1")
	// SymbolSpotDONNYTESTUSDT :
	SymbolSpotDONNYTESTUSDT = SymbolSpot("DONNYTESTUSDT")
	// SymbolSpotEOSBIT :
	SymbolSpotEOSBIT = SymbolSpot("EOSBIT")
	// SymbolSpotXLMQQT :
	SymbolSpotXLMQQT = SymbolSpot("XLMQQT")
	// SymbolSpotLTCXLM :
	SymbolSpotLTCXLM = SymbolSpot("LTCXLM")
	// SymbolSpotXLMEOS :
	SymbolSpotXLMEOS = SymbolSpot("XLMEOS")
	// SymbolSpotXLMXRP :
	SymbolSpotXLMXRP = SymbolSpot("XLMXRP")
	// SymbolSpotXLMSHIBI :
	SymbolSpotXLMSHIBI = SymbolSpot("XLMSHIBI")
	// SymbolSpotXLMTRX :
	SymbolSpotXLMTRX = SymbolSpot("XLMTRX")
	// SymbolSpotXLMMFT :
	SymbolSpotXLMMFT = SymbolSpot("XLMMFT")
	// SymbolSpotXLMQTHQ :
	SymbolSpotXLMQTHQ = SymbolSpot("XLMQTHQ")
	// SymbolSpotXLMNEO :
	SymbolSpotXLMNEO = SymbolSpot("XLMNEO")
	// SymbolSpotUNILTC :
	SymbolSpotUNILTC = SymbolSpot("UNILTC")
	// SymbolSpotUNINEO :
	SymbolSpotUNINEO = SymbolSpot("UNINEO")
	// SymbolSpotBTC3SUSDT :
	SymbolSpotBTC3SUSDT = SymbolSpot("BTC3SUSDT")
	// SymbolSpotBTC3LUSDT :
	SymbolSpotBTC3LUSDT = SymbolSpot("BTC3LUSDT")
	// SymbolSpotQTHQQQT :
	SymbolSpotQTHQQQT = SymbolSpot("QTHQQQT")
	// SymbolSpotETH3LUSDT :
	SymbolSpotETH3LUSDT = SymbolSpot("ETH3LUSDT")
	// SymbolSpotSPOTTEST3USDT :
	SymbolSpotSPOTTEST3USDT = SymbolSpot("SPOTTEST3USDT")
	// SymbolSpotPMTEST12ETH :
	SymbolSpotPMTEST12ETH = SymbolSpot("PMTEST12ETH")
	// SymbolSpotPMTEST12UST :
	SymbolSpotPMTEST12UST = SymbolSpot("PMTEST12UST")
	// SymbolSpotUSDTUST :
	SymbolSpotUSDTUST = SymbolSpot("USDTUST")
	// SymbolSpotPMTEST12DAI :
	SymbolSpotPMTEST12DAI = SymbolSpot("PMTEST12DAI")
	// SymbolSpotUSDTDAI :
	SymbolSpotUSDTDAI = SymbolSpot("USDTDAI")
	// SymbolSpotXXXXYFI :
	SymbolSpotXXXXYFI = SymbolSpot("XXXXYFI")
	// SymbolSpotUSTCUSDT :
	SymbolSpotUSTCUSDT = SymbolSpot("USTCUSDT")
	// SymbolSpotDONNYTEST02USDT :
	SymbolSpotDONNYTEST02USDT = SymbolSpot("DONNYTEST02USDT")
	// SymbolSpotPMTEST047USDT :
	SymbolSpotPMTEST047USDT = SymbolSpot("PMTEST047USDT")
	// SymbolSpotPMTESTAUSDT :
	SymbolSpotPMTESTAUSDT = SymbolSpot("PMTESTAUSDT")
	// SymbolSpotXRPBIT :
	SymbolSpotXRPBIT = SymbolSpot("XRPBIT")
	// SymbolSpotPMTESTCUSDT :
	SymbolSpotPMTESTCUSDT = SymbolSpot("PMTESTCUSDT")
	// SymbolSpotPMTESTZUSDT :
	SymbolSpotPMTESTZUSDT = SymbolSpot("PMTESTZUSDT")
	// SymbolSpotPMTESTBUSDT :
	SymbolSpotPMTESTBUSDT = SymbolSpot("PMTESTBUSDT")
	// SymbolSpotPMTESTDUSDT :
	SymbolSpotPMTESTDUSDT = SymbolSpot("PMTESTDUSDT")
	// SymbolSpotPMTESTABTC :
	SymbolSpotPMTESTABTC = SymbolSpot("PMTESTABTC")
	// SymbolSpotDYDXETH :
	SymbolSpotDYDXETH = SymbolSpot("DYDXETH")
	// SymbolSpotDYDXQQT :
	SymbolSpotDYDXQQT = SymbolSpot("DYDXQQT")
	// SymbolSpotNEODYDX :
	SymbolSpotNEODYDX = SymbolSpot("NEODYDX")
	// SymbolSpotDYDXXRP :
	SymbolSpotDYDXXRP = SymbolSpot("DYDXXRP")
	// SymbolSpotEOSDYDX :
	SymbolSpotEOSDYDX = SymbolSpot("EOSDYDX")
	// SymbolSpotDYDXNEO :
	SymbolSpotDYDXNEO = SymbolSpot("DYDXNEO")
	// SymbolSpotDYDXDOGE :
	SymbolSpotDYDXDOGE = SymbolSpot("DYDXDOGE")
	// SymbolSpotDOGEDYDX :
	SymbolSpotDOGEDYDX = SymbolSpot("DOGEDYDX")
	// SymbolSpotMFTDYDX :
	SymbolSpotMFTDYDX = SymbolSpot("MFTDYDX")
	// SymbolSpotXRPDYDX :
	SymbolSpotXRPDYDX = SymbolSpot("XRPDYDX")
	// SymbolSpotETHDYDX :
	SymbolSpotETHDYDX = SymbolSpot("ETHDYDX")
	// SymbolSpotQQTDYDX :
	SymbolSpotQQTDYDX = SymbolSpot("QQTDYDX")
	// SymbolSpotDYDXPIG :
	SymbolSpotDYDXPIG = SymbolSpot("DYDXPIG")
	// SymbolSpotQQTHT :
	SymbolSpotQQTHT = SymbolSpot("QQTHT")
	// SymbolSpotEOSHT :
	SymbolSpotEOSHT = SymbolSpot("EOSHT")
	// SymbolSpotHTQQT :
	SymbolSpotHTQQT = SymbolSpot("HTQQT")
	// SymbolSpotHTEOS :
	SymbolSpotHTEOS = SymbolSpot("HTEOS")
	// SymbolSpotMVUSDT :
	SymbolSpotMVUSDT = SymbolSpot("MVUSDT")
	// SymbolSpotBTCBIT :
	SymbolSpotBTCBIT = SymbolSpot("BTCBIT")
	// SymbolSpotPMTESTEUSDT :
	SymbolSpotPMTESTEUSDT = SymbolSpot("PMTESTEUSDT")
	// SymbolSpotPMTEST2USDC :
	SymbolSpotPMTEST2USDC = SymbolSpot("PMTEST2USDC")
	// SymbolSpotPMTEST6USDC :
	SymbolSpotPMTEST6USDC = SymbolSpot("PMTEST6USDC")
	// SymbolSpotADAUSDC :
	SymbolSpotADAUSDC = SymbolSpot("ADAUSDC")
	// SymbolSpotUSDTTEST :
	SymbolSpotUSDTTEST = SymbolSpot("USDTTEST")
	// SymbolSpotBTCTEST :
	SymbolSpotBTCTEST = SymbolSpot("BTCTEST")
	// SymbolSpotPMTEST12USDT :
	SymbolSpotPMTEST12USDT = SymbolSpot("PMTEST12USDT")
	// SymbolSpotPMTEST12BTC :
	SymbolSpotPMTEST12BTC = SymbolSpot("PMTEST12BTC")
	// SymbolSpotPORTUGALUSDT :
	SymbolSpotPORTUGALUSDT = SymbolSpot("PORTUGALUSDT")
	// SymbolSpotEOS3LUSDT :
	SymbolSpotEOS3LUSDT = SymbolSpot("EOS3LUSDT")
	// SymbolSpotGRPCUSDT :
	SymbolSpotGRPCUSDT = SymbolSpot("GRPCUSDT")
	// SymbolSpotGRPCBTC :
	SymbolSpotGRPCBTC = SymbolSpot("GRPCBTC")
	// SymbolSpotUSDTETH :
	SymbolSpotUSDTETH = SymbolSpot("USDTETH")
	// SymbolSpotGRPCETH :
	SymbolSpotGRPCETH = SymbolSpot("GRPCETH")
	// SymbolSpotPORTUGALEOS :
	SymbolSpotPORTUGALEOS = SymbolSpot("PORTUGALEOS")
	// SymbolSpotPMTEST03EOS :
	SymbolSpotPMTEST03EOS = SymbolSpot("PMTEST03EOS")
	// SymbolSpotPMTEST03ETH :
	SymbolSpotPMTEST03ETH = SymbolSpot("PMTEST03ETH")
	// SymbolSpotPMTEST03XRP :
	SymbolSpotPMTEST03XRP = SymbolSpot("PMTEST03XRP")
	// SymbolSpotDFGUSDT :
	SymbolSpotDFGUSDT = SymbolSpot("DFGUSDT")
	// SymbolSpotLANG1ETH :
	SymbolSpotLANG1ETH = SymbolSpot("LANG1ETH")
	// SymbolSpotSOLOETH :
	SymbolSpotSOLOETH = SymbolSpot("SOLOETH")
	// SymbolSpotSOLOUSDT :
	SymbolSpotSOLOUSDT = SymbolSpot("SOLOUSDT")
	// SymbolSpotWERUSDT :
	SymbolSpotWERUSDT = SymbolSpot("WERUSDT")
	// SymbolSpotTESTTUSDT :
	SymbolSpotTESTTUSDT = SymbolSpot("TESTTUSDT")
	// SymbolSpotSOL3SUSDT :
	SymbolSpotSOL3SUSDT = SymbolSpot("SOL3SUSDT")
	// SymbolSpotSOL3LUSDT :
	SymbolSpotSOL3LUSDT = SymbolSpot("SOL3LUSDT")
	// SymbolSpotAAVEBTC :
	SymbolSpotAAVEBTC = SymbolSpot("AAVEBTC")
	// SymbolSpotXLMBTC :
	SymbolSpotXLMBTC = SymbolSpot("XLMBTC")
	// SymbolSpotLTCBTC :
	SymbolSpotLTCBTC = SymbolSpot("LTCBTC")
	// SymbolSpotPMTEST16USDT :
	SymbolSpotPMTEST16USDT = SymbolSpot("PMTEST16USDT")
	// SymbolSpotFFFFUSDT :
	SymbolSpotFFFFUSDT = SymbolSpot("FFFFUSDT")
	// SymbolSpotPORTUGALETH :
	SymbolSpotPORTUGALETH = SymbolSpot("PORTUGALETH")
	// SymbolSpotZENUSDT :
	SymbolSpotZENUSDT = SymbolSpot("ZENUSDT")
	// SymbolSpotSOS3LBTC :
	SymbolSpotSOS3LBTC = SymbolSpot("SOS3LBTC")
	// SymbolSpotSOS3SUSDT :
	SymbolSpotSOS3SUSDT = SymbolSpot("SOS3SUSDT")
	// SymbolSpotSOS3LUSDT :
	SymbolSpotSOS3LUSDT = SymbolSpot("SOS3LUSDT")
	// SymbolSpotICXUSDT :
	SymbolSpotICXUSDT = SymbolSpot("ICXUSDT")
	// SymbolSpotSTXUSDT :
	SymbolSpotSTXUSDT = SymbolSpot("STXUSDT")
	// SymbolSpotSOLBIT :
	SymbolSpotSOLBIT = SymbolSpot("SOLBIT")
	// SymbolSpotPMTEST001USDT :
	SymbolSpotPMTEST001USDT = SymbolSpot("PMTEST001USDT")
	// SymbolSpotSOLEOS :
	SymbolSpotSOLEOS = SymbolSpot("SOLEOS")
	// SymbolSpotTRIBLUSDT :
	SymbolSpotTRIBLUSDT = SymbolSpot("TRIBLUSDT")
	// SymbolSpotBTGETH :
	SymbolSpotBTGETH = SymbolSpot("BTGETH")
	// SymbolSpotAVAXUSDT :
	SymbolSpotAVAXUSDT = SymbolSpot("AVAXUSDT")
	// SymbolSpotSANDUSDT :
	SymbolSpotSANDUSDT = SymbolSpot("SANDUSDT")
	// SymbolSpotBTGUSDC :
	SymbolSpotBTGUSDC = SymbolSpot("BTGUSDC")
	// SymbolSpotBTGBIT :
	SymbolSpotBTGBIT = SymbolSpot("BTGBIT")
	// SymbolSpotBTTETH :
	SymbolSpotBTTETH = SymbolSpot("BTTETH")
	// SymbolSpotBUSDUSDT :
	SymbolSpotBUSDUSDT = SymbolSpot("BUSDUSDT")
	// SymbolSpotNEOEOS :
	SymbolSpotNEOEOS = SymbolSpot("NEOEOS")
	// SymbolSpotHNTUSDT :
	SymbolSpotHNTUSDT = SymbolSpot("HNTUSDT")
	// SymbolSpotNEOETH :
	SymbolSpotNEOETH = SymbolSpot("NEOETH")
	// SymbolSpotUNIETH :
	SymbolSpotUNIETH = SymbolSpot("UNIETH")
	// SymbolSpotLUNCEOS :
	SymbolSpotLUNCEOS = SymbolSpot("LUNCEOS")
	// SymbolSpotLUNCXRP :
	SymbolSpotLUNCXRP = SymbolSpot("LUNCXRP")
	// SymbolSpotNEOBIT :
	SymbolSpotNEOBIT = SymbolSpot("NEOBIT")
	// SymbolSpotDOGEBRL :
	SymbolSpotDOGEBRL = SymbolSpot("DOGEBRL")
	// SymbolSpotBRLUSDT :
	SymbolSpotBRLUSDT = SymbolSpot("BRLUSDT")
	// SymbolSpotSOLUSD :
	SymbolSpotSOLUSD = SymbolSpot("SOLUSD")
	// SymbolSpotUSDEUR :
	SymbolSpotUSDEUR = SymbolSpot("USDEUR")
	// SymbolSpotUSDTEUR :
	SymbolSpotUSDTEUR = SymbolSpot("USDTEUR")
	// SymbolSpotUSDTUSD :
	SymbolSpotUSDTUSD = SymbolSpot("USDTUSD")
	// SymbolSpotSOLUSDC :
	SymbolSpotSOLUSDC = SymbolSpot("SOLUSDC")
	// SymbolSpotDOTUSDC :
	SymbolSpotDOTUSDC = SymbolSpot("DOTUSDC")
	// SymbolSpotXRPUSDC :
	SymbolSpotXRPUSDC = SymbolSpot("XRPUSDC")
	// SymbolSpotBITUSDC :
	SymbolSpotBITUSDC = SymbolSpot("BITUSDC")
	// SymbolSpotPMTEST15BTC :
	SymbolSpotPMTEST15BTC = SymbolSpot("PMTEST15BTC")
	// SymbolSpotDCRUSDT :
	SymbolSpotDCRUSDT = SymbolSpot("DCRUSDT")
	// SymbolSpotEOSDAI :
	SymbolSpotEOSDAI = SymbolSpot("EOSDAI")
	// SymbolSpotSHIBIDAI :
	SymbolSpotSHIBIDAI = SymbolSpot("SHIBIDAI")
)
