name: golangci-lint

on:
  push:
    branches: '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v3.4.0
          args: --disable-all --enable=errcheck,staticcheck,govet,unused,structcheck,gosimple
